logging:
  level:
    org.spring.framework.cloud.kubernetes: DEBUG
spring:  application:    name: config-example
    
management:
  endpoints:
    web:
      exposure:        include: info,refresh,keepalive,health  
    